backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "hero"
    label: "Sezione Iniziale"
    files:
      - file: "content/hero.md"
        label: "Contenuti Intestazione"
        name: "hero"
        fields:
          - { label: "Titolo principale", name: "title", widget: "string" }
          - { label: "Paragrafo", name: "paragraph", widget: "text" }
          - { label: "Testo bottone", name: "button_text", widget: "string" }
          - { label: "Link bottone", name: "button_url", widget: "string" }

  - name: "servizi"
    label: "Card Servizi"
    folder: "content/servizi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo servizio", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Immagine", name: "image", widget: "image" }
